title: Abdelrhman's Portfolio
author: GitHub User
email:abdelrhmannabil96@gmail.com


social links
twitter_username: Abdelrhman Nabil Ibraheem
github_username:  abdelrhmannabil

linkedin_username: Abdelrhman Nabil Ibraheem

show_excerpts: false # set to true to show excerpts on the homepage

theme: minima
